"author:charan
"gmail:charancuz008@gmail.com

"set guicursor
set gcr=a:block-blinkon0 "fat cursor - cursor blink
set linespace=0

" Set extra options when running in GUI mode
if has("gui_running")

    set guioptions-=m "menu bar
    set guioptions-=T "tool bar
    set guioptions+=e "tab line gui or cli

    "remove scrollbars
	set guioptions-=rL

	"ui
	set guioptions+=Cd

endif

set wak=no
set showtabline=2 "always show tabs


command ToggleFullscreen {
	if &guioptions =~# 's'
		set guioptions-=s
	else
		set guioptions+=s
	endif
}

map <expr> <F11> &go =~# 's' ? ":se go-=s<CR>" : ":se go+=s<CR>"
