"author:charan
"gmail:charancuz008@gmail.com

set guicursor=a:block-blinkon0 "fat cursor - cursor blink
set winaltkeys=no

if has("gui_running")

	set linespace=0

	set guioptions-=m "menu bar
	set guioptions-=T "tool bar
	set guioptions-=e "tab line gui or cli

	"remove scrollbars
	set guioptions-=rL

	"hl-TitleBar
	set guioptions+=Cd

endif

" seee :h gui-w32-fullscreen
map <expr> <F11> &go =~# 's' ? ":se go-=s<CR>" : ":se go+=s<CR>"
