iab ch charan
iab mal charancuz008gmail.com
set nocp "i strongly discourage it

filetype plugin indent on " Enable filetype plugins
syntax on" Enable syntax highlighting

let mapleader=' '

packadd comment "vims default
packadd nohlsearch "performs noh aut

"-------------------------------------------------------------

colo retrobox
set autoindent "Auto indent
set autoread  " Set to auto read when a file is changed from the outside
set background=dark
set belloff=all
set cmdheight=1 " Height of the command bar (default)
set colorcolumn=80 "Will make screen redrawing slower
set concealcursor=nc "conceals cursor 
set cursorline
set cursorlineopt=number "just hi the number
set encoding=utf8 " Set utf8 as standard encoding and en_US as the standard language
set ffs=unix,dos,mac " Use Unix as the standard file type
set foldcolumn=1 
set gcr=a:block "fat cursor --vim.o.guicursor=""
set hid " A buffer becomes hidden when it is abandoned
set hlsearch " Highlight search results
set ignorecase " Ignore case when searching
set incsearch " Makes search act like search in modern browsers
set laststatus=2 " always show statusline 
set lazyredraw " Don't redraw while executing macros (good performance config)
set noexpandtab
set nojoinspaces "J doesnt join spaces 
set noshowmatch " matching bracks
set noswapfile "no swaps
set nowrap "noWrap lines
set nowritebackup
set number " show line numbers
set path+=** "make the find to search through dirs and subdirs
set regexpengine=0 "performance on windows"
set relativenumber " show relativeline numbers
set ruler " Always show current position
set scrolloff=7
set shiftwidth=4
set shortmess+=I  "disables the start page
set showtabpanel=0 "only vimm
set smartcase " When searching try to be smart about cases
set smartindent 
set smarttab
set softtabstop-=1"inherit from shiftwidth
set tabstop=4
set termguicolors
set timeoutlen=500
set title
set whichwrap+=<,>,h,l "makes cursor move from one to another at ends
set wildmenu " Turn on the Wild menu

" ->KEYMAPS
"-------------------------------------------------------------- 

nnoremap <Esc><Esc> <Cmd>nohlsearch<CR>

nnoremap <leader>w <Cmd>update<CR>
nnoremap <leader>bs <Cmd>ls<CR>:b<Space>
nnoremap <leader>bd <Cmd>bd<CR>
nnoremap <leader>te :tabe<Space>

nnoremap <leader>y :%y+<CR> |"system clipboard
xnoremap <leader>y "+y  |"system clipboard for all visual modes

tnoremap >   |"terminal mode >cuz yazi uses term
