[flavor]
dark = "everforest-medium"

# no icons!!
[indicator]
padding = { open = "", close = "" }
[tabs]
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }

[cmp]
icon_file = ""
icon_folder = ""
# or use unicode icon_file = "📄"

[icon]
globs = []
dirs  = []
files = []
exts  = []
conds = []
