"-- Author: charan
"-- Gmail:  charancuz008@gmail.com

"  General
let mapleader=' '
set history=500 " Sets how many lines of history VIM has to remember

"vim plug --ontop
call plug#begin('~/.vim/plugged')

" Plug 'morhetz/gruvbox'
Plug 'lifepillar/vim-solarized8'
Plug 'jiangmiao/auto-pairs'
Plug 'preservim/nerdtree'
"Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
"Plug 'junegunn/fzf.vim'
"Plug 'vim-airline/vim-airline'
Plug 'christoomey/vim-tmux-navigator' "somehow making ctrl-w to easy maps
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'vimwiki/vimwiki'
Plug 'mattn/calendar-vim'

call plug#end()

" VIM UI
"-------------------------------------------------------------
set gcr=a:block "fat cursor --vim.o.guicursor=""
set so=7
"set clipboard=unnamedplus "integration with system clipboard register
set shortmess+=I  "disables the start page
set wildmenu " Turn on the Wild menu
set ruler " Always show current position
set number " show line numbers
set relativenumber " show relativeline numbers
set cmdheight=1 " Height of the command bar
set foldcolumn=1 " Add a bit extra margin to the left
" set colorcolumn=80


" VIM UX
"-------------------------------------------------------------
set hid " A buffer becomes hidden when it is abandoned
set backspace=eol,start,indent " Configure backspace so it acts as it should act
set whichwrap+=<,>,h,l
set ignorecase " Ignore case when searching
set smartcase " When searching try to be smart about cases
set hlsearch " Highlight search results
set incsearch " Makes search act like search in modern browsers
set lazyredraw " Don't redraw while executing macros (good performance config)
set magic " For regular expressions turn magic on
set noshowmatch " Show matching brackets when text indicator is over them
" set mat=2 "How many tenths of a second to blink when matching brackets
"
" No annoying sound on errors
set noerrorbells
set novisualbell
set belloff=all
set t_vb=
set tm=500


"Colors and Fonts
"-------------------------------------------------------------
syntax enable " Enable syntax highlighting
set regexpengine=0 " Set regular expression engine automatically
se tgc "termguicolors
if $COLORTERM == 'alacritty' " Enable 256 colors palette 
    set t_Co=256
endif
set background=light "dark

"solarized
let g:solarized_statusline = "flat"
colorscheme solarized8_high

" Files, backups and undo
" ------------------------------------------------------------
filetype plugin on " Enable filetype plugins
filetype indent on
set autoread  " Set to auto read when a file is changed from the outside
set encoding=utf8 " Set utf8 as standard encoding and en_US as the standard language
set ffs=unix,dos,mac " Use Unix as the standard file type

set nobackup " Turn backup off
set nowb
set noswapfile "no swaps


" Text, tab and indent related
"-------------------------------------------------------------- 
set noexpandtab
set smarttab
set shiftwidth=4
set tabstop=4
set ai "Auto indent
set si "Smart indent
set nowrap "noWrap lines

"-- misc
"-------------------------------------------------------------- 
se nojoinspaces "J doesnt join spaces 
se concealcursor=nc "conceals cursor 
autocmd FileType c,cpp setlocal cindent "c-style indent

"-- plgn-spe-conf
"-------------------------------------------------------------- 
"
let g:vimwiki_list = [{'path': 'G:/My Drive/notes', 'syntax': 'markdown','ext': '.md'}]  "vimwiki

nnoremap <leader>e :NERDTreeToggle<CR>  | "nerdtree toggle


" ->KEYMAPS

" different keymaps for easy peasy coding

autocmd BufNewFile *.cpp 0r C:/Users/chr_58/Desktop/dotfilez/tmplt/cp/template.cpp  "template

:tnoremap <Esc> <C-\><C-n> "To map <Esc> to exit terminal-mode: >vim

nnoremap <Esc><Esc> :noh<Return><Esc>  "hlsearch creates an annoyance so instead of noh press ese esc


