[env]
TERM= "screen-256color"

[terminal.shell]
program= "cmd.exe"
args = []

[general]
import = [
	"gruber_darker.toml"
]

working_directory = "C:\\Users\\chr_58"

[window]

opacity = 1

padding.x = 0
padding.y = 0
dynamic_padding = true

title="~"
dynamic_title=true

decorations ="Full"
decorations_theme_variant = "Dark"

[font]

# normal.family = "IBM Plex Mono"
# bold.family = "IBM Plex Mono"
# italic.family = "IBM Plex Mono"
# bold_italic.family = "IBM Plex Mono"

# size = 13.0

offset = { x = 0, y = 1 }

[cursor]
style = {shape="Block",blinking="Never"}
unfocused_hollow = true

[keyboard]

bindings = [
{ key="F11", action="ToggleFullscreen" },
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "Space", mods="Control",action = "ToggleViMode" },
]

[colors]
draw_bold_text_with_bright_colors = true
# cursor = { text = "CellBackground" ,cursor = "#cb4b16" } #red
# cursor = { text = "CellBackground" ,cursor = "#51afef" } #blue
# cursor = { text = "CellBackground" ,cursor = "#00ff00"} #green
cursor = { text = "CellBackground" ,cursor = "#d3c6aa" } #everforest
