[env]
TERM = "screen-256color"

[general]
import = [
	"win32.toml"
]

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
# opacity = 0.925
title="~"
decorations_theme_variant = "Dark"

[font]
# normal.family = "Courier New"
# size = 12
offset = { x = 1, y = 1 }

# from: https://github.com/vim/colorschemes/blob/master/colortemplate/quiet.colortemplate
[colors]
primary = {foreground = "#dadada",background = "#181818"}
cursor = { text = "CellBackground" ,cursor = "#f4f4ff" } #wez
vi_mode_cursor = { text = "CellBackground" ,cursor = "#51afef" } #(diff from matches and vim search)
search = {
	matches = { foreground = "#181818", background = "#00afff" },
	focused_match = { foreground = "#181818", background = "#ff5fff" }
}
# line_indicator = { foreground = "None", background = "#ffaf00" }
footer_bar = { foreground = "#a8a8a8", background = "#2c2c2c" }
selection = { text = "CellBackground", background = "#ffaf00" }
# draw_bold_text_with_bright_colors = true #bright foreground??

# TODO alacritty defaults are great
# cursor = { text = "CellBackground" ,cursor = "#cb4b16" } #red
# cursor = { text = "CellBackground" ,cursor = "#51afef" } #blue
# cursor = { text = "CellBackground" ,cursor = "#00ff00"} #green
# cursor = { text = "CellBackground" ,cursor = "#d3c6aa" } #everforest

[cursor]
style = {shape="Block",blinking="Never"}
unfocused_hollow = true
thickness = 0.3 #for search

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
{ key="F11", action="ToggleFullscreen" },
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "Space", mods="Control",action = "ToggleViMode" }, #vim abbreviation trigger :? cmd.exe uses <C-M>
{ key = "[", mods="Control",mode="Vi|~Search",action = "ClearSelection" }, #<C-c>
{ key = "[", mods="Control",mode="Search",action = "SearchCancel" }, #<C-c>
# TODO readline motions for footer_bar
]

# https://alacritty.org/config-alacritty-bindings.html
# https://alacritty.org/config-alacritty.html
